// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvtD6CyHjrHnfYbwN9k0vBTm1LSxtWsgg',
    appId: '1:541467084034:web:2461019c5ee11c87dc2e1b',
    messagingSenderId: '541467084034',
    projectId: 'chatapp-21811',
    authDomain: 'chatapp-21811.firebaseapp.com',
    storageBucket: 'chatapp-21811.firebasestorage.app',
    measurementId: 'G-YKBG5H4NFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2lMrR_3GNGqXgQ4b7nN8D-JyWi7srt8I',
    appId: '1:541467084034:android:77a12e5ed6a6d382dc2e1b',
    messagingSenderId: '541467084034',
    projectId: 'chatapp-21811',
    storageBucket: 'chatapp-21811.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzhWPPu61aYlLEC0KrmIneB1TkBJROkCY',
    appId: '1:541467084034:ios:0372b7f7d31f6fbadc2e1b',
    messagingSenderId: '541467084034',
    projectId: 'chatapp-21811',
    storageBucket: 'chatapp-21811.firebasestorage.app',
    iosBundleId: 'com.example.woho',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzhWPPu61aYlLEC0KrmIneB1TkBJROkCY',
    appId: '1:541467084034:ios:0372b7f7d31f6fbadc2e1b',
    messagingSenderId: '541467084034',
    projectId: 'chatapp-21811',
    storageBucket: 'chatapp-21811.firebasestorage.app',
    iosBundleId: 'com.example.woho',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvtD6CyHjrHnfYbwN9k0vBTm1LSxtWsgg',
    appId: '1:541467084034:web:b11cedecad94547adc2e1b',
    messagingSenderId: '541467084034',
    projectId: 'chatapp-21811',
    authDomain: 'chatapp-21811.firebaseapp.com',
    storageBucket: 'chatapp-21811.firebasestorage.app',
    measurementId: 'G-Z8WCFN5PHC',
  );
}
